### PR TITLE
Log more details about the response from the test server.

### LINKED ISSUE #3968: Behat Tests Failing
This may be related to https://github.com/acquia/blt/issues/1382.

**I want to...**
Upgrade to BLT 11, Drush 10, etc.

**It's not working because...**
Behat tests are not executing due to the server not starting. Note that if I go into ci.blt.yml and change the value of `tests.run-server` from true to false, then it seems to work fine. I'm not sure why it was ok prior to this update and not post? Maybe a drush thing?

**Detailed error output**
```
blt tests:all --define drush.alias='${drush.aliases.ci}' -D behat.web-driver=chrome --no-interaction --ansi --verbose
> tests:behat:run
> tests:server:start
[info] Killing all processing containing string 'runserver'...
[info] Killing all processes on port '8888'...
Launching PHP's internal web server via drush.
[info] Running server at http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[error]  Timed out.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/
Drush logged the following errors while attempting to start the web server:
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
[error]  Command `tests:server:start ` exited with code 1. This most likely indicates a problem with your configuration, and is not a BLT bug.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
[error]  Command `tests:behat:run ` exited with code 1. This most likely indicates a problem with your configuration, and is not a BLT bug.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
01:01 total time elapsed.
pipelines_kill_background_processes
pstree -p $$ | grep -E -o '([0-9]+)' | grep -v "^$$\$" | sort -k2 -rn
Killing background jobs
```

**BLT doctor output**
```
lando blt doctor
+---------------------------+--------------------------------------------+
| Property                  | Value                                      |
+---------------------------+--------------------------------------------+
| %paths.%root              | /app/docroot                               |
| %paths.%site              | sites/default                              |
| %paths.%modules           | sites/all/modules                          |
| %paths.%themes            | sites/all/themes                           |
| %paths.%config-sync       | /app/config/default                        |
| %paths.%files             | sites/default/files                        |
| %paths.%temp              | /tmp                                       |
| %paths.%private           | /app/files-private                         |
| admin-theme               | seven                                      |
| alias-searchpaths.0       | /app/drush/sites                           |
| base-profile              |                                            |
| blt-version               | 11.0.1                                     |
| bootstrap                 | Successful                                 |
| composer-version          | Composer version 1.8.4 2019-02-11 10:52:10 |
| config-sync               | /app/config/default                        |
| db-driver                 | mysql                                      |
| db-hostname               | database                                   |
| db-name                   | drupal8                                    |
| db-password               | drupal8                                    |
| db-port                   | 3306                                       |
| db-status                 | Connected                                  |
| db-username               | drupal8                                    |
| drupal-settings-file      | sites/default/settings.php                 |
| drupal-version            | 8.8.1                                      |
| drush-alias-files.0       | /app/drush/sites/capitalcamp.site.yml      |
| drush-alias-files.1       | /app/drush/sites/dgc.site.yml              |
| drush-cache-directory     | /var/www/.drush/cache                      |
| drush-conf.0              | /app/vendor/drush/drush/drush.yml          |
| drush-conf.1              | /app/drush/drush.yml                       |
| drush-conf.2              | /app/docroot/sites/default/local.drush.yml |
| drush-script              | /app/vendor/drush/drush/drush              |
| drush-temp                | /tmp                                       |
| drush-version             | 10.1.1                                     |
| files                     | sites/default/files                        |
| install-profile           | lightning                                  |
| modules                   | sites/all/modules                          |
| php-bin                   | /usr/local/bin/php                         |
| php-conf.1                | false                                      |
| php-os                    | Linux                                      |
| private                   | /app/files-private                         |
| root                      | /app/docroot                               |
| site                      | sites/default                              |
| stacks.drupal-vm.inited   | false                                      |
| stacks.dev-desktop.inited | false                                      |
| temp                      | /tmp                                       |
| theme                     | twentynineteen                             |
| themes                    | sites/all/themes                           |
| uri                       | http://local.capitalcamp.com               |
+---------------------------+--------------------------------------------+
+----------------------------------------------+--------------------------------------------------------------+
| Check                                        | Problem                                                      |
+----------------------------------------------+--------------------------------------------------------------+
| BehatCheck:checkBaseUrl:uri                  | base_url in tests/behat/local.yml does not match the site    |
|                                              | URI.                                                         |
|                                              |   Behat base_url is set to                                   |
|                                              | http://drupalgovcon.lndo.site.                               |
|                                              |   Drush site URI is set to                                   |
|                                              | http://local.capitalcamp.com.                                |
| ComposerCheck:composer.extra.installer-paths | The Composer configuration for extra.installer-paths differs |
|                                              | from BLT's default, recommended values.                      |
|                                              |   Change your configuration to match BLT's defaults in       |
|                                              |                                                              |
|                                              | vendor/acquia/blt/subtree-splits/blt-project/composer.json.  |
| NodeCheck:checkNodeVersionFileExists         | .node-version file exists                                    |
| WebUriCheck:checkUriResponse                 | Did not get a response from http://local.capitalcamp.com     |
|                                              | Is your *AMP stack running?                                  |
|                                              | Is your /etc/hosts file correctly configured?                |
|                                              | Is your web server configured to serve this URI from         |
|                                              | /app/docroot?                                                |
|                                              | Is options.uri set correctly in                              |
|                                              | /app/docroot/sites/default/local.drush.yml?                  |
+----------------------------------------------+--------------------------------------------------------------+
[error]  BLT Doctor discovered one or more critical issues.
```

**System information**
* Operating system type: Mac OS
* Operating system version: Catalina
* BLT version: 11.1

### PR DESCRIPTION
**Pull request by davidtrainer**
Fixes #3968  
--------

Changes proposed
---------
Make BLT's log output during automated tests more informative

Steps to replicate the issue
----------
1. Run a CI build in which the app returns a 500 after the setup-app step. 

Previous (bad) behavior, before applying PR
----------
My tests were failing in the exact same way as #3968 , but for a different reason. The drush runserver was started successfully, but responding with a 500 due to the kind of fatal error reported in https://github.com/acquia/blt/pull/4068

This took me a while to realize, because the output from BLT indicates that we are waiting for a response from the server, which never responds, so we eventually get a timeout error:

```
[info] Waiting for response from http://127.0.0.1:8888...

[info] Waiting for response from http://127.0.0.1:8888...

[info] Waiting for response from http://127.0.0.1:8888...

[error]  Timed out.
```

What's actually happening is that `waitForUrlAvailable` is waiting for a *non-50x* response, but without any further details, it looks like there is no response received at all.

Expected behavior, after applying PR and re-running test steps
-----------
This patch updates the message from `waitForUrlAvailable` for better clarity, and updates `checkUrl` so that each failed check reports the code and body of the response:

```
[info] Waiting for response from http://127.0.0.1:8888...

[info] Response code: 500

[info] The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">Symfony\Component\Routing\Exception\RouteNotFoundException</em>: Route &quot;cohesion.error_logger&quot; does not exist. in <em class="placeholder">Drupal\Core\Routing\RouteProvider-&gt;getRouteByName()</em> (line <em class="placeholder">208</em> of <em class="placeholder">core/lib/Drupal/Core/Routing/RouteProvider.php</em>). <pre class="backtrace">Drupal\Core\Routing\UrlGenerator-&gt;getRoute(&#039;cohesion.error_logger&#039;) (Line: 271)
Drupal\Core\Routing\UrlGenerator-&gt;generateFromRoute(&#039;cohesion.error_logger&#039;, Array, Array, 1) (Line: 105)
Drupal\Core\Render\MetadataBubblingUrlGenerator-&gt;generateFromRoute(&#039;cohesion.error_logger&#039;, Array, Array, ) (Line: 754)
Drupal\Core\Url-&gt;toString() (Line: 278)
cohesion_page_attachments(Array) (Line: 297)
Drupal\Core\Render\MainContent\HtmlRenderer-&gt;invokePageAttachmentHooks(Array) (Line: 273)
Drupal\Core\Render\MainContent\HtmlRenderer-&gt;prepare(Array, Object, Object) (Line: 117)
Drupal\Core\Render\MainContent\HtmlRenderer-&gt;renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber-&gt;onViewRenderArray(Object, &#039;kernel.view&#039;, Object)
call_user_func(Array, Object, &#039;kernel.view&#039;, Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher-&gt;dispatch(&#039;kernel.view&#039;, Object) (Line: 156)
Symfony\Component\HttpKernel\HttpKernel-&gt;handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel-&gt;handle(Object, 1, 1) (Line: 67)
Drupal\simple_oauth\HttpMiddleware\BasicAuthSwap-&gt;handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session-&gt;handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle-&gt;handle(Object, 1, 1) (Line: 191)
Drupal\page_cache\StackMiddleware\PageCache-&gt;fetch(Object, 1, 1) (Line: 128)
Drupal\page_cache\StackMiddleware\PageCache-&gt;lookup(Object, 1, 1) (Line: 82)
Drupal\page_cache\StackMiddleware\PageCache-&gt;handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware-&gt;handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware-&gt;handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel-&gt;handle(Object, 1, 1) (Line: 694)
Drupal\Core\DrupalKernel-&gt;handle(Object) (Line: 19)
</pre>

[error]  Timed out.
```

Additional details
-----------
The response body is already sent to a debug log (`$this->logger->debug($res->getBody());`) but since this is happening in a Pipelines CI environment, I'm not sure where to find that.

### CODE REVIEW

**Comment by mikemadison13** [comment]
this is much needed IMHO, as the fatal errors / 500 errors during testing look like a funky response (not an error).

File: src/Robo/Common/Executor.php [hunk 1]
```diff
@@ -223,6 +223,8 @@ public function checkUrl($url) {
         return TRUE;
       }
       else {
+        $this->logger->info("Response code: " . $res->getStatusCode());
```
Comment (danepowell) [inline src/Robo/Common/Executor.php:226]: Since we ping urls every second or so for some operations (waiting for Drush server to spin up, for instance), doesn't printing the status code and body every time seem awfully verbose? Could this be a debug statement instead (so you'd see it with `blt -vvv`?

Comment (davidtrainer) [reply src/Robo/Common/Executor.php:226]: Yeah, I agree.

**Comment by mikemadison13** [comment]
is this something we could also wire into the drush debug mode in the ci.blt.yml file? does that automatically flag -vvv when enabled?
