### PR TITLE
Issue 1543

### LINKED ISSUE #1543: Twig Lint is not maintained and fails valid twig code
My system information:
* Operating system type: OSX/drupal-vm
* Operating system version: Sierra/drupal-vm 4.3
* BLT version: 8.7

When I run this command:
```
blt validate:twig
```

I get the following output:
(Removed some project specific paths and file names)
```
blt > validate:twig:
     [echo] Validating twig syntax for all custom modules and themes...
KO in [path/to/]templates/content/node--[somecontenttype].html.twig (line 22)
   20           #}
   21           {% for image in node.field_product_offering_images %}
>> 22             {% set isRowEnd = loop.index is divisible by(4) %}
>> Unexpected token "name" of value "by" ("end of statement block" expected).
   23             {% set imageUrl = image.url %}
   24             {% set imageTitle = image.title %}
```

And I expected this to happen:
`divisible by(4)` is valid twig syntax and should not fail https://twig.sensiolabs.org/doc/1.x/tests/divisibleby.html

There's an issue on the twig lint project and a couple of PRs that haven't been updated since 2015 for this problem

https://github.com/asm89/twig-lint/issues/25
https://github.com/asm89/twig-lint/issues/33

PR that would address:
https://github.com/asm89/twig-lint/pull/23

Filing this as it looks like we should probably patch this somehow, or find another linter that is being more actively maintained.

### PR DESCRIPTION
**Pull request by wu-edward**
Fixes #1543.

Changes proposed:
- Remove asm89/twig-lint and use Symfony twig linter
- Run twig lint command procedurally instead of in parallel, otherwise error messages are suppressed.
- Account for Twig functions and filters added by Drupal, so that linter does not flag as invalid.
- Provide config for users to add custom Twig filters and functions that can be specified in project.yml
- Reorder precommit lint commands so that PHPUnit tests do not fail on Travis.

### CODE REVIEW

File: src/Robo/Commands/Git/GitCommand.php [hunk 1]
```diff
@@ -47,13 +47,16 @@ public function commitMsgHook($message) {
    * @return int
    */
   public function preCommitHook($changed_files) {
+    $changed_files_list = explode("\n", $changed_files);
     $this->invokeCommands([
+      // Passing a file list to be PHPCS will cause all specified files to
```
Comment (grasmash) [inline src/Robo/Commands/Git/GitCommand.php]: We don't need to add this comment back :)

File: src/Robo/Blt.php [hunk 2]
```diff
@@ -116,6 +120,46 @@ private function addPluginsCommandsAndHooks() {
   }
 
   /**
+   * Adds Symfony (non-Robo) command classes to the application.
+   *
+   * @param \Acquia\Blt\Robo\Application $application
+   */
+  protected function addSymfonyCommands(Application $application) {
```
Comment (grasmash) [inline src/Robo/Blt.php]: I do wish we could move this out of the Blt.php file. It feels like it doesn't belong here.

File: src/Robo/Commands/Git/GitCommand.php (hunk 1 above)
Comment (wu-edward) [reply src/Robo/Commands/Git/GitCommand.php]: I refactored and removed all the changes to this class.

File: src/Robo/Blt.php (hunk 2 above)
Comment (wu-edward) [reply src/Robo/Blt.php]: I agree, so I refactored and put everything in the TwigCommand class. I think it's cleaner now.
