### PR TITLE
Fixes #2658 by moving sanitize command out of hook and into blt command.

### LINKED ISSUE #2658: Acquia cloud hook db-scrub.sh not working
My system information:
* Operating system type: Acquia environment
* Operating system version: Acquia
* BLT version: 9.0.4

When I run this command:
```
[2018-03-20 19:41:32] [2018-03-20 19:41:31] Starting hook: post-db-copy
[2018-03-20 19:41:31] Executing: /mnt/users/mfgov/dev.shell /var/www/html/mfgov.dev/hooks/common/post-db-copy/1-db-scrub.sh mfgov dev mfgov prod < /dev/null (as mfgov.dev@staging-11739})

```

I get the following output:
```
site="$1"
target_env="$2"
db_name="$3"
source_env="$4"

acsf_file="/mnt/files/$AH_SITE_GROUP.$AH_SITE_ENVIRONMENT/files-private/sites.json"
if [ ! -f $acsf_file ]; then
  echo "$site.$target_env: Scrubbing database $db_name"
  drush @$site.$target_env sql-sanitize --sanitize-password="$(openssl rand -base64 32)" --yes
  drush @$site.$target_env cache-rebuild
fi
mfgov.dev: Scrubbing database mfgov
ArgumentCountError: Too few arguments to function Drush\Sql\SqlBase::__construct(), 1 passed and exactly 2 expected in Drush\Sql\SqlBase->__construct() (line 34 of /mnt/www/html/mfgovdev/vendor/drush/drush/src/Sql/SqlBase.php).
Drush command terminated abnormally due to an unrecoverable error.       [error]
[2018-03-20 19:41:32] Finished hook: post-db-copy

[2018-03-20 19:41:32] Not sending webhook hook: 'post-db-copy' revision: ''
[2018-03-20 19:41:32] WARN: Command returned exit code 1: /mnt/users/mfgov/dev.shell /var/www/html/mfgov.dev/hooks/common/post-db-copy/1-db-scrub.sh mfgov dev mfgov prod executing hook post-db-copy
zlib(finalizer): the stream was freed prematurely.
```

And I expected this to happen:
The hook to run correctly.

### PR DESCRIPTION
**Pull request by mikemadison13**
Fixes #2658  .

Changes proposed:
- adds a custom blt artifact script that handles the sanitization
- testing for new script

### CODE REVIEW

File: src/Robo/Commands/Artifact/AcHooksCommand.php [hunk 1]
```diff
@@ -71,6 +71,30 @@ public function postCodeUpdate($site, $target_env, $source_branch, $deployed_tag
...
+   * @param string $target_env
+   *   The cloud env. E.g., dev
+   *
+   * @command artifact:ac-hooks:db-scrub
+   *
+   * @throws \Exception
+   */
+  public function dbScrub($site, $target_env) {
+    $this->taskDrush()
+      ->drush("sql-sanitize --sanitize-password=\"$(openssl rand -base64 32)\" --yes")
```
Comment (grasmash) [inline src/Robo/Commands/Artifact/AcHooksCommand.php]: Since we are in PHP, I'd prefer to generate the random password in PHP. See https://github.com/acquia/blt/blob/9.x/src/Robo/Commands/Setup/DrupalCommand.php#L31

File: scripts/cloud-hooks/hooks/common/post-db-copy/db-scrub.sh [hunk 2]
```diff
@@ -15,9 +15,13 @@ source_env="$4"
...
 if [ ! -f $acsf_file ]; then
-  echo "$site.$target_env: Scrubbing database $db_name"
-  drush @$site.$target_env sql-sanitize --sanitize-password="$(openssl rand -base64 32)" --yes
-  drush @$site.$target_env cache-rebuild
+  # Prep for BLT commands.
+  repo_root="/var/www/html/$site.$target_env"
+  export PATH=$repo_root/vendor/bin:$PATH
+  cd $repo_root
+
+blt artifact:ac-hooks:db-scrub $site $target_env
```
Comment (grasmash) [inline scripts/cloud-hooks/hooks/common/post-db-copy/db-scrub.sh]: Shouldn't this be indented?

File: src/Robo/Commands/Artifact/AcHooksCommand.php [hunk 3]
```diff
@@ -71,6 +71,30 @@ public function postCodeUpdate($site, $target_env, $source_branch, $deployed_tag
...
+   * @param string $site
+   *   The site name. E.g., site1.
+   * @param string $target_env
+   *   The cloud env. E.g., dev
+   *
+   * @command artifact:ac-hooks:db-scrub
+   *
+   * @throws \Exception
+   */
+  public function dbScrub($site, $target_env) {
```
Comment (grasmash) [inline src/Robo/Commands/Artifact/AcHooksCommand.php]: I'd prefer to pass all available arguments to the command, `$site, $target_env, $source_branch, $deployed_tag, $repo_url, $repo_type`. This would allow BLT to make use of these in the future without requiring a new major version or re-generation of hooks.

Comment (mikemadison13) [reply src/Robo/Commands/Artifact/AcHooksCommand.php]: @grasmash i can update, but the db-scrub has these variables (not exactly the same as you mention above):

```
site="$1"
target_env="$2"
db_name="$3"
source_env="$4"
```

Comment (mikemadison13) [reply src/Robo/Commands/Artifact/AcHooksCommand.php]: thoughts?
