### PR TITLE
Fixes #2760: Leverage source and target dump options for sync.

### LINKED ISSUE #2760: Errors when running blt sync:refresh for sites on the same host
My system information:
* Operating system type: Linux 
* Operating system version: CentOS 6.9
* BLT version: 9.0.5

Output of `blt doctor`:
```
+---------------------------+--------------------------------------------------------------+
| Property                  | Value                                                        |
+---------------------------+--------------------------------------------------------------+
| %paths.%root              | /var/www/site2/src/docroot                                   |
| %paths.%site              | sites/default                                                |
| %paths.%modules           | sites/all/modules                                            |
| %paths.%themes            | sites/all/themes                                             |
| %paths.%config-sync       | /var/www/site2/src/config/default                            |
| alias-searchpaths.0       | /var/www/site2/src/drush/sites                               |
| blt-version               | 9.0.5                                                        |
| composer-version          | Composer version 1.4.1 2017-03-10 09:29:45                   |
| config-sync               | /var/www/site2/src/config/default                            |
| db-driver                 | mysql                                                        |
| db-hostname               | localhost                                                    |
| db-name                   | drupal                                                       |
| db-password               | drupal                                                       |
| db-port                   | 3306                                                         |
| db-username               | drupal                                                       |
| drupal-settings-file      | sites/default/settings.php                                   |
| drupal-version            | 8.5.2                                                        |
| drush-alias-files.0       | /var/www/site2/src/drush/sites/dev.site.yml                  |
| drush-conf.0              | /var/www/site2/src/vendor/drush/drush/drush.yml              |
| drush-conf.1              | /var/www/site2/src/drush/drush.yml                           |
| drush-conf.2              | /var/www/site2/src/docroot/sites/default/local.drush.yml     |
| drush-script              | /var/www/site2/src/vendor/bin/drush                          |
| drush-temp                | /tmp                                                         |
| drush-version             | 9.2.3                                                        |
| modules                   | sites/all/modules                                            |
| php-bin                   | /usr/bin/php                                                 |
| php-conf.0                | /etc/php.ini                                                 |
| php-os                    | Linux                                                        |
| root                      | /var/www/site2/src/docroot                                   |
| site                      | sites/default                                                |
| stacks.drupal-vm.inited   | false                                                        |
| stacks.dev-desktop.inited | false                                                        |
| themes                    | sites/all/themes                                             |
| uri                       | http://site2.localhost                                       |
+---------------------------+--------------------------------------------------------------+
+------------------------------------------+--------------------------------------------------------------+
| Check                                    | Problem                                                      |
+------------------------------------------+--------------------------------------------------------------+
| BehatCheck:checkLocalConfig:exists       | tests/behat/local.yml is missing!                            |
|                                          |   Run `blt tests:behat:init:config` to generate it from      |
|                                          | example.local.yml.                                           |
| ComposerCheck:checkPrestissimo:plugins   | hirak/prestissimo plugin for composer is not installed.      |
|                                          |   Run composer global require                                |
|                                          | hirak/prestissimo to install it.                             |
|                                          |   This will improve composer install/update performance by   |
|                                          | parallelizing the download of dependency information.        |
| DrupalCheck:checkDrupalBootstrapped      | Could not bootstrap Drupal via drush without alias.          |
| DrupalCheck:checkDrupalInstalled         | Drupal is not installed.                                     |
|                                          |                                                              |
|                                          | Run `blt drupal:install` to install Drupal locally.          |
| FileSystemCheck:checkFileSystem:%files   | Public files directory is not set.                           |
| FileSystemCheck:checkFileSystem:%private | Private files directory is not set.                          |
| FileSystemCheck:checkFileSystem:%temp    | Temporary files directory is not set.                        |
| NodeCheck:checkNodeVersionFileExists     | Neither .nvmrc nor .node-version file found in repo root.    |
| WebUriCheck:checkUriResponse             | Did not get a response from http://bisnode.localhost         |
|                                          | Is your *AMP stack running?                                  |
|                                          | Is your /etc/hosts file correctly configured?                |
|                                          | Is your web server configured to serve this URI from         |
|                                          | /var/www/site2/src/docroot?                                  |
|                                          | Is options.uri set correctly in                              |
|                                          | /var/www/site2/src/docroot/sites/default/local.drush.yml?    |
+------------------------------------------+--------------------------------------------------------------+
[error]  BLT Doctor discovered one or more critical issues.


```

When I run this command:
```bash
blt sync:refresh
```

I get the following output:
```
 [error]  File(s) not found: /tmp/tmp.sql.gz
 [error]  Failed to import /tmp/tmp.sql.gz into target
```
Test scenario:
Have the same site twice (or more) on one host. Drush aliases are correctly set.

When running `blt sync:refresh` on site2 the following is run:
```bash
 /var/www/site2/vendor/bin/drush sql-sync @site1 @self --source-dump=/tmp/tmp.sql --structure-tables-key=lightweight --create-db --no-interaction --ansi
```
Running this manually with the `--debug` option shows that `drush` uses `rsync`:
```bash
rsync -e 'ssh ' -akzv  --stats --progress --remove-source-files user@10.10.10.10:/tmp/tmp.sql.gz /tmp/tmp.sql.gz
```
10.10.10.10 is the IP address of the current host.
This causes `/tmp/tmp.sql.gz` to be deleted after "transfer" before drush imports it.

Looking at https://github.com/acquia/blt/blob/9.x/src/Robo/Commands/Sync/SyncCommand.php#L137 and having in mind the permissions issue #2641, I propose to create a subfolder in `/tmp` and pass it as `--source-dump` so that the sql-sync command looks like this:

```bash
mkdir /tmp/blt
 /var/www/site2/vendor/bin/drush sql-sync @site1 @self --source-dump=/tmp/blt/tmp.sql --structure-tables-key=lightweight --create-db --no-interaction --ansi
```
This causes drush to execute `rsync` as:
```bash
rsync -e 'ssh ' -akzv  --stats --progress --remove-source-files user@10.10.10.10:/tmp/blt/tmp.sql.gz /tmp/tmp.sql.gz
```
which does remove the source file, but it's different from the destination.

### PR DESCRIPTION
**Pull request by malikkotob**

### CODE REVIEW

File: src/Robo/Commands/Sync/SyncCommand.php [hunk 1]
```diff
@@ -134,7 +134,8 @@ public function syncDb() {
       ->arg($local_alias)
       // @see https://github.com/drush-ops/drush/releases/tag/9.2.1
       // @see https://github.com/acquia/blt/issues/2641
-      ->option('--source-dump', sys_get_temp_dir() . '/tmp.sql')
+      ->option('--source-dump', sys_get_temp_dir() . '/tmp.source.sql')
+      ->option('--target-dump', sys_get_temp_dir() . '/tmp.target.sql.gz')
```
Comment (grasmash) [inline src/Robo/Commands/Sync/SyncCommand.php]: Odd these have different extensions?

Comment (malikkotob) [reply src/Robo/Commands/Sync/SyncCommand.php]: It is odd. I initially had it without the `gz` and it failed on `gzip -d /tmp/tmp.target.sql`. Documentation is poor for these options, but I sifted through the issue queue and stumbled upon this PR that was merged into an old drush version - https://github.com/drush-ops/drush/pull/1996/files. It shows the `target-dump` option with the `gz` extension.
