### PR TITLE
Fix logic to make sure user config directory exists.

### LINKED ISSUE #4078: No such file or directory user.json
**Describe the bug**
After starting a new BLT 12.x-dev project (with a Lando VM) I am getting a lot of errors with the " Do you want to help us make this tool even better? (y/n)" question. It isn't saving either response in the VM.

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. Run `create-project --no-interaction acquia/blt-project:12.x-dev canary9`
2. Copy the Drupal GovCon .lando file (and rename to whatever for the VM)
3. Run `lando start`
4. Run `lando blt setup`
5. See errors

**Expected behavior**
I only have to answer the question once.

**Detailed error output**
```
We strive to give you the best tools for development.
You can really help us improve by sharing anonymous performance and usage data.

 Do you want to help us make this tool even better? (y/n) n
PHP Warning:  file_put_contents(/var/www/.config/blt/user.json): failed to open stream: No such file or directory in /app/vendor/acquia/blt/src/Robo/Common/UserConfig.php on line 113

Warning: file_put_contents(/var/www/.config/blt/user.json): failed to open stream: No such file or directory in /app/vendor/acquia/blt/src/Robo/Common/UserConfig.php on line 113
Ok, no data will be tracked and reported.
We take privacy seriously.
Installing pre-commit git hook...
Installing pre-push git hook...
Installing commit-msg git hook...
> blt:init:settings
We strive to give you the best tools for development.
You can really help us improve by sharing anonymous performance and usage data.

 Do you want to help us make this tool even better? (y/n) n
PHP Warning:  file_put_contents(/var/www/.config/blt/user.json): failed to open stream: No such file or directory in /app/vendor/acquia/blt/src/Robo/Common/UserConfig.php on line 113

Warning: file_put_contents(/var/www/.config/blt/user.json): failed to open stream: No such file or directory in /app/vendor/acquia/blt/src/Robo/Common/UserConfig.php on line 113
Ok, no data will be tracked and reported.
We take privacy seriously.
Hash salt already exists.
> source:build:frontend
We strive to give you the best tools for development.
You can really help us improve by sharing anonymous performance and usage data.

 Do you want to help us make this tool even better? (y/n) n
PHP Warning:  file_put_contents(/var/www/.config/blt/user.json): failed to open stream: No such file or directory in /app/vendor/acquia/blt/src/Robo/Common/UserConfig.php on line 113

Warning: file_put_contents(/var/www/.config/blt/user.json): failed to open stream: No such file or directory in /app/vendor/acquia/blt/src/Robo/Common/UserConfig.php on line 113
Ok, no data will be tracked and reported.
We take privacy seriously.
> source:build:frontend-reqs
We strive to give you the best tools for development.
You can really help us improve by sharing anonymous performance and usage data.
```

**BLT doctor output**
```
lando blt doctor

There is an update available!!!
Install it to get the latest and greatest

Updating helps us provide the best support.
https://github.com/lando/lando/releases/tag/v3.0.0-rrc.1

If you are updating from 3.0.0-rc.1 or below it is CRITICAL you read the following docs first
https://thinktandem.io/blog/2019/02/01/lando-is-ready-for-the-masses-with-rc2-release/
https://docs.devwithlando.io/guides/updating-to-rc2.html
We strive to give you the best tools for development.
You can really help us improve by sharing anonymous performance and usage data.

 Do you want to help us make this tool even better? (y/n) n
PHP Warning:  file_put_contents(/var/www/.config/blt/user.json): failed to open stream: No such file or directory in /app/vendor/acquia/blt/src/Robo/Common/UserConfig.php on line 113

Warning: file_put_contents(/var/www/.config/blt/user.json): failed to open stream: No such file or directory in /app/vendor/acquia/blt/src/Robo/Common/UserConfig.php on line 113
Ok, no data will be tracked and reported.
We take privacy seriously.
+---------------------------+--------------------------------------------+
| Property                  | Value                                      |
+---------------------------+--------------------------------------------+
| %paths.%root              | /app/docroot                               |
| %paths.%site              | sites/default                              |
| %paths.%modules           | sites/all/modules                          |
| %paths.%themes            | sites/all/themes                           |
| %paths.%config-sync       | /app/config/default                        |
| alias-searchpaths.0       | /app/drush/sites                           |
| blt-version               | 11.2.0                                     |
| composer-version          | Composer version 1.9.0 2019-08-02 20:55:32 |
| config-sync               | /app/config/default                        |
| db-driver                 | mysql                                      |
| db-hostname               | localhost                                  |
| db-name                   | drupal                                     |
| db-password               | drupal                                     |
| db-port                   | 3306                                       |
| db-username               | drupal                                     |
| drupal-settings-file      | sites/default/settings.php                 |
| drupal-version            | 9.0.0-beta1                                |
| drush-cache-directory     | /var/www/.drush/cache                      |
| drush-conf.0              | /app/vendor/drush/drush/drush.yml          |
| drush-conf.1              | /app/drush/drush.yml                       |
| drush-conf.2              | /app/docroot/sites/default/local.drush.yml |
| drush-script              | /app/vendor/drush/drush/drush              |
| drush-temp                | /tmp                                       |
| drush-version             | 10.2.2                                     |
| modules                   | sites/all/modules                          |
| php-bin                   | /usr/local/bin/php                         |
| php-conf.1                | false                                      |
| php-os                    | Linux                                      |
| root                      | /app/docroot                               |
| site                      | sites/default                              |
| stacks.drupal-vm.inited   | false                                      |
| stacks.dev-desktop.inited | false                                      |
| themes                    | sites/all/themes                           |
| uri                       | http://local.blted10.com                   |
+---------------------------+--------------------------------------------+
+------------------------------------------+--------------------------------------------------------------+
| Check                                    | Problem                                                      |
+------------------------------------------+--------------------------------------------------------------+
| BehatCheck:checkBaseUrl:uri              | base_url in tests/behat/local.yml does not match the site    |
|                                          | URI.                                                         |
|                                          |   Behat base_url is set to                                   |
|                                          | http://canary.lndo.site.                                     |
|                                          |   Drush site URI is set to                                   |
|                                          | http://local.blted10.com.                                    |
| ConfigCheck:checkGitConfig               | Git repositories are not defined in blt.yml.                 |
|                                          |   Add values for git.remotes to blt.yml to enabled automated |
|                                          | deployment.                                                  |
| DbCheck:checkDbConnection                | Could not connect to database.                               |
|                                          |                                                              |
|                                          | Is your *AMP stack running?                                  |
|                                          | Are your database credentials correct?                       |
|                                          |   db-driver: mysql                                           |
|                                          |   db-hostname: localhost                                     |
|                                          |   db-username: drupal                                        |
|                                          |   db-password: drupal                                        |
|                                          |   db-name: drupal                                            |
|                                          |   db-port: 3306                                              |
|                                          |                                                              |
|                                          | To verify your mysql credentials, run `mysql -u drupal -h    |
|                                          | localhost -pdrupal -P 3306`                                  |
|                                          |                                                              |
|                                          | Are you using the correct PHP binary?                        |
|                                          | Is PHP using the correct MySQL socket?                       |
|                                          |   php-os: Linux                                              |
|                                          |   php-bin: /usr/local/bin/php                                |
|                                          |   php-conf:                                                  |
|                                          |                                                              |
|                                          | Are you using the correct site and settings.php file?        |
|                                          |   site: sites/default                                        |
|                                          |   drupal-settings-file: sites/default/settings.php           |
|                                          |                                                              |
|                                          | To verify, run `drush sqlc`                                  |
|                                          |                                                              |
| DrupalCheck:checkDrupalBootstrapped      | Could not bootstrap Drupal via drush without alias.          |
| DrupalCheck:checkDrupalInstalled         | Drupal is not installed.                                     |
|                                          |                                                              |
|                                          | Run `blt drupal:install` to install Drupal locally.          |
| FileSystemCheck:checkFileSystem:%files   | Public files directory is not set.                           |
| FileSystemCheck:checkFileSystem:%private | Private files directory is not set.                          |
| FileSystemCheck:checkFileSystem:%temp    | Temporary files directory is not set.                        |
| NodeCheck:checkNodeVersionFileExists     | Neither .nvmrc nor .node-version file found in repo root.    |
| WebUriCheck:checkUriResponse             | Did not get a response from http://local.blted10.com         |
|                                          | Is your *AMP stack running?                                  |
|                                          | Is your /etc/hosts file correctly configured?                |
|                                          | Is your web server configured to serve this URI from         |
|                                          | /app/docroot?                                                |
|                                          | Is options.uri set correctly in                              |
|                                          | /app/docroot/sites/default/local.drush.yml?                  |
+------------------------------------------+--------------------------------------------------------------+
[error]  BLT Doctor discovered one or more critical issues.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
```

**System information**
* BLT version: 12.x-dev

**Additional context**
Beginning to test Drupal 9.

### PR DESCRIPTION
**Pull request by wu-edward**
Fixes #4078
See https://github.com/acquia/blt/issues/4078#issuecomment-612097471 for explanation.

### CODE REVIEW

File: src/Robo/Common/UserConfig.php [hunk 1]
```diff
@@ -38,15 +38,9 @@ public function __construct(string $configDir) {
...
     }
     else {
-      if (!file_exists($configDir)) {
-        if (is_writable(dirname($configDir))) {
-          mkdir($configDir, 0777, TRUE);
-        }
-        else {
-          return;
-        }
+      if (!file_exists($configDir) && mkdir($configDir, 0777, TRUE)) {
```
Comment (danepowell) [inline src/Robo/Common/UserConfig.php:41]: I think you're on the right path, but won't this fail to create the json file if for some reason the directory exists but the json file doesn't?

Comment (wu-edward) [reply src/Robo/Common/UserConfig.php]: Nice catch. Updated PR.
