### PR TITLE
Fixes #2633: Make git hook symlinks relative.

### LINKED ISSUE #2633: BLT git hooks symlinks are broken outside the VM
My system information:
* Operating system type: Mac / Drupal VM 4.8.1
* Operating system version: Sierra / beet/box
* BLT version: 9.0.3

Output of `blt doctor`:
```
$ blt doctor
[warning] The xDebug extension is loaded. This will significantly decrease performance.
+---------------------------+---------------------------------------------------------+
| Property                  | Value                                                   |
+---------------------------+---------------------------------------------------------+
| %paths.%root              | /var/www/mfgov-d8/docroot                               |
| %paths.%site              | sites/default                                           |
| %paths.%modules           | sites/all/modules                                       |
| %paths.%themes            | sites/all/themes                                        |
| %paths.%config-sync       | /var/www/mfgov-d8/config/default                        |
| %paths.%files             | sites/default/files                                     |
| %paths.%temp              | /tmp                                                    |
| %paths.%private           | /var/www/mfgov-d8/files-private                         |
| admin-theme               | seven                                                   |
| alias-searchpaths.0       | /var/www/mfgov-d8/drush/sites                           |
| blt-version               | 9.0.3                                                   |
| bootstrap                 | Successful                                              |
| composer-version          | Composer version 1.6.3 2018-01-31 16:28:17              |
| config-sync               | /var/www/mfgov-d8/config/default                        |
| db-driver                 | mysql                                                   |
| db-hostname               | localhost                                               |
| db-name                   | drupal                                                  |
| db-password               | drupal                                                  |
| db-port                   | 3306                                                    |
| db-status                 | Connected                                               |
| db-username               | drupal                                                  |
| drupal-settings-file      | sites/default/settings.php                              |
| drupal-version            | 8.5.0                                                   |
| drush-alias-files.0       | /var/www/mfgov-d8/drush/sites/mfgov.site.yml            |
| drush-conf.0              | /var/www/mfgov-d8/vendor/drush/drush/drush.yml          |
| drush-conf.1              | /var/www/mfgov-d8/drush/drush.yml                       |
| drush-conf.2              | /var/www/mfgov-d8/docroot/sites/default/local.drush.yml |
| drush-script              | /var/www/mfgov-d8/vendor/bin/drush                      |
| drush-temp                | /tmp                                                    |
| drush-version             | 9.2.1                                                   |
| files                     | sites/default/files                                     |
| install-profile           | lightning                                               |
| modules                   | sites/all/modules                                       |
| php-bin                   | /usr/bin/php7.1                                         |
| php-conf.0                | /etc/php/7.1/cli/php.ini                                |
| php-os                    | Linux                                                   |
| private                   | /var/www/mfgov-d8/files-private                         |
| root                      | /var/www/mfgov-d8/docroot                               |
| site                      | sites/default                                           |
| stacks.drupal-vm.inited   | true                                                    |
| stacks.dev-desktop.inited | false                                                   |
| temp                      | /tmp                                                    |
| theme                     | uswds_mfgov                                             |
| themes                    | sites/all/themes                                        |
| uri                       | https://local.manufacturing.test                        |
+---------------------------+---------------------------------------------------------+
+--------------------------------------+-----------------------------------------------------------+
| Check                                | Problem                                                   |
+--------------------------------------+-----------------------------------------------------------+
| NodeCheck:checkNodeVersionFileExists | Neither .nvmrc nor .node-version file found in repo root. |
| WebUriCheck:checkHttps               | The SSL certificate for your local site appears to be     |
|                                      | invalid for https://local.manufacturing.test.             |
+--------------------------------------+-----------------------------------------------------------+
[error]  BLT Doctor discovered one or more critical issues. 
```

When I run this command (from outside the VM):
```
git commit -m "This is my invalid, not very good commit message?"
```

I get the following output (a successful commit, but no pre-commit checks or commit message validation):
```
[OAM-131 a733b22] This is my invalid, not very good commit message?
 1 file changed, 1 insertion(+)
```

And I expected this to happen:
Git to complain about my improperly formatted commit message as defined in .git/hooks/commit-msg (a symlink to /var/www/mfgov-d8/vendor/acquia/blt/scripts/git-hooks/commit-msg). Obviously this symlink is bad/incorrect outside the VM.

Does BLT recommend that even git commits be performed inside the VM?

Could the BLT Robo task which creates the symlink make it a relative one, so it will work inside and outside the VM?

### PR DESCRIPTION
**Pull request by malikkotob**

### CODE REVIEW

File: src/Robo/Commands/Setup/SettingsCommand.php [hunk 1]
```diff
@@ -217,15 +217,16 @@ public function gitHooks() {
   protected function installGitHook($hook) {
     if ($this->getConfigValue('git.hooks.' . $hook)) {
       $this->say("Installing $hook git hook...");
-      $source = $this->getConfigValue('git.hooks.' . $hook) . "/$hook";
-      $dest = $this->getConfigValue('repo.root') . "/.git/hooks/$hook";
+      $bltHook = $this->getConfigValue('git.hooks.' . $hook) . "/$hook";
```
Comment (grasmash) [inline src/Robo/Commands/Setup/SettingsCommand.php]: This isn't necessarily a BLT hook, it could be custom. Why not name it something like `$source_hook`?

File: src/Robo/Commands/Setup/SettingsCommand.php [hunk 2]
```diff
@@ -217,15 +217,16 @@ public function gitHooks() {
...
+      $projectHookDirectory = $this->getConfigValue('repo.root') . "/.git/hooks";
```
Comment (grasmash) [inline src/Robo/Commands/Setup/SettingsCommand.php]: Non-class property variables should be camel case.

**Comment by grasmash** [comment]
Be sure to add test that asserts the symlink location is valid.

File: src/Robo/Commands/Setup/SettingsCommand.php (hunk 1 above)
Comment (malikkotob) [reply src/Robo/Commands/Setup/SettingsCommand.php]: hmm, it's a BLT hook in the sense that it's the hook that ships with BLT in it's vendor directory:
```
  hooks:
    pre-commit: ${blt.root}/scripts/git-hooks
    commit-msg: ${blt.root}/scripts/git-hooks
```

Comment (malikkotob) [reply src/Robo/Commands/Setup/SettingsCommand.php]: I can change it to `$hook_source` if you prefer, was thinking it was essentially a "blt provided hook"

File: src/Robo/Commands/Setup/SettingsCommand.php (hunk 2 above)
Comment (malikkotob) [reply src/Robo/Commands/Setup/SettingsCommand.php]: noted!

File: tests/phpunit/BltProject/SetupGitHooksTest.php [hunk 3]
```diff
@@ -16,8 +16,17 @@ class GitTasksTest extends BltProjectTestBase {
   public function testGitConfig() {
     $this->blt("blt:init:git-hooks");
     $this->assertFileExists($this->sandboxInstance . '/.git');
-    $this->assertFileExists($this->sandboxInstance . '/.git/hooks/commit-msg');
-    $this->assertFileExists($this->sandboxInstance . '/.git/hooks/pre-commit');
+    $hooks_path = $this->sandboxInstance . '/.git/hooks';
+    $hook_names = [
```
Comment (grasmash) [inline tests/phpunit/BltProject/SetupGitHooksTest.php]: You can load this list from config.
