### PR TITLE
Warn users that BLT is supported on Windows only under WSL. Updated documentation with alternatives.

### LINKED ISSUE #3359: "BLT installation failed! Please execute C:/Users/
My system information:
* Operating system type: [Windows] 
* Operating system version: [Windows 10]
* BLT version: [9.2]

Output of `blt doctor`:
```
[

![52077064-0f93aa80-255e-11e9-91f6-1e8e5ccc4d31](https://user-images.githubusercontent.com/46496452/52139005-d8d09980-261c-11e9-87cd-a05200b01110.png)


]
```

When I run this command:
``` 
[composer create-project --no-interaction acquia/blt-project blt-project]
```

I get the following output:
```
"BLT installation failed! Please execute C:/Users/Mjobe/projects/BLT-Project/vendor/acquia/blt/bin/blt internal:create-project --ansi --verbose to debug the issue.
"
[replace with ENTIRE command output. DO NOT enter partial output.
![image](https://user-images.githubusercontent.com/46496452/52139053-061d4780-261d-11e9-9538-aab917206f15.png)

![image](https://user-images.githubusercontent.com/46496452/52138852-61026f00-261c-11e9-90dd-5a84a20cd274.png)


 ran
C:/Users/Mjobe/projects/BLT-Project/vendor/acquia/blt/bin/blt internal:create-project --ansi --verbose

![image](https://user-images.githubusercontent.com/46496452/52138873-74add580-261c-11e9-82f2-be0a94f5f756.png)
]
```

And I expected this to happen:

### PR DESCRIPTION
**Pull request by alexxed**
Fixes #3359 
--------

Changes proposed:
---------
Stop the BLT installation with an error if it's attempted on Windows (cmd.exe, cygwin, mingw32, anything other than WSL). Added documentation for workarounds.

Steps to verify the solution:
-----------
Run in babun, or cmd.exe, or cygwin on Windows:
`php composer.phar create-project acquia/blt-project --repository='{"type":"vcs","url":"git@github.com:alexxed/blt-project","reference":"3359"}' blt-test -s dev`

blt failed

### CODE REVIEW

**Comment by danepowell** [comment]
Thanks, I'll test later. Code looks good at first glance. Only one concern.

Are we certain that there's no possibility that people could be using BLT on Windows? Aborting the install is pretty radical, I just want to make sure that we're not alienating anyone who might have found a way to do it that we're just not aware of.

**Comment by alexxed** [comment]
See my comments in https://github.com/acquia/blt/issues/3359. I don't see a way to make it work without changing code:
- symfony/process that uses proc_open and on Windows sets bypass_shell to false, so composer will try to execute vendor/bin/blt as a windows binary
- under cygwin, you have the path problem
- under regular windows, you don't have the posix extensions

But to be on the safe side, we can change the PR to abort just on new installs, not on updates.

**Comment by danepowell** [comment]
Yeah, I think I'd prefer if this only aborted on new installs. It can still warn in all cases.

File: src/Composer/Plugin.php [hunk 1]
```diff
@@ -151,10 +162,10 @@ protected function executeBltUpdate($version) {
       $this->io->write('<info>Creating BLT templated files...</info>');
       if ($this->isNewProject()) {
         // The BLT command will not work at this point because the .git dir doesn't exist yet.
-        $command = $this->getVendorPath() . '/acquia/blt/bin/blt internal:create-project --ansi';
+        $command = str_replace('\\', '/', PHP_BINDIR) . '/php ' . $this->getVendorPath() . '/acquia/blt/bin/blt internal:create-project --ansi --verbose';
```
Comment (danepowell) [inline src/Composer/Plugin.php]: Why are you calling blt via the php binary here? Was something wrong with calling blt directly?

Additionally, why the hardcoded verbose option? This makes the output significantly more verbose and probably isn't desirable. Ideally this would inherit if someone uses `composer create-project --verbose`, but maybe that's a follow-up.

Comment (alexxed) [reply src/Composer/Plugin.php]: Oh, this got in by mistake, I was trying to fix the windows problems. I'll remove it.
