### PR TITLE
Fixes #3704: Pin Chromedriver to 74 on TravisCI

### LINKED ISSUE #3704: All chromedriver tests fail with 400 Bad Request error
**I want to...**
Address `FunctionalJavascript` (chromedriver) test failures.

This is likely an upstream issue, but perhaps a workaround can be investigated for BLT users pending an upstream fix.

**It's not working because...**
All tests which require a user to log in fail at the login step with: `The requested URL returned error: 400 Bad Request`. The same thing is occurring within BLT's internal tests. See [here](https://travis-ci.com/acquia/blt/jobs/206614349#L2503) for instance.

**System information**
* Operating system type: `Linux`
* Operating system version: `Ubuntu 14.04.5`
* BLT version: `10.x`

### PR DESCRIPTION
**Pull request by danepowell**
Fixes #3704 
--------

Changes proposed
---------
- Chromedriver 75 introduces a breaking change that makes it impossible to run Drupal core tests, as well as many other Behat tests. Pin to 74 until that's resolved.

Steps to replicate the issue
----------
1. See that all of our tests (for PHPUNIT_GROUP=drupal) were previously failing, and now pass with this PR.

### CODE REVIEW

File: scripts/linux/install-chrome.sh [hunk 1]
```diff
@@ -14,7 +14,10 @@ if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
 
   # Installs chromedriver for Linux 64 bit systems.
   LATEST_CHROMEDRIVER=$(wget -q -O - http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
-  wget -N http://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER/chromedriver_linux64.zip
+  # wget -N http://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER/chromedriver_linux64.zip
+  # Temporarily pin to Chromedriver 74.
+  # @see https://github.com/acquia/blt/issues/3704
+  wget -N https://chromedriver.storage.googleapis.com/74.0.3729.6/chromedriver_linux64.zip
```
Comment (bobbygryzynger) [inline scripts/linux/install-chrome.sh]: Just a thought here: it might make sense to make the version value an environment variable with `74.0.3729.6` as its default for now. This would make it easier for projects using this script to set a different version.

**Comment by danepowell** [comment]
@bobbygryzynger @dpagini this lets you set the desired version via `$CHROMEDRIVER_VERSION` in `.travis.yml` if you prefer a different version. Look good?

**Comment by dpagini** [comment]
> @bobbygryzynger @dpagini this lets you set the desired version via $CHROMEDRIVER_VERSION in .travis.yml if you prefer a different version. Look good?

Sorry, I just gave it a thumbs up b/c I thought it was a good idea. Makes sense to me!  😄
